### ISSUE TITLE
0.1.7 StringVectorExample fails to compile

### ISSUE THREAD

**Issue by lancewilson-monash** [eddelbuettel/rcppexamples#2]
RcppExamples 0.1.7 can't be installed from CRAN repository on linux machines as compile fails. Please see the following error:

`g++ -I/usr/local/R/3.2.1/lib64/R/include -DNDEBUG  -I/usr/local/openmpi/1.8.2-gcc/include -I/usr/local/gcc/4.9.1/include/c++/4.9.1/x86_64-unknown-linux-gnu/ -I/usr/local/gcc/4.9.1/include -I/usr/local/mpc/1.0.2/include -I/usr/local/mpfr/3.1.2/include -I/usr/local/gmp/6.0.0/include -I"/usr/local/R/3.2.1/lib64/R/library/Rcpp/include"   -fpic  -g -O2  -c StringVectorExample.cpp -o StringVectorExample.o
In file included from /usr/local/gcc/4.9.1/include/c++/4.9.1/algorithm:62:0,
                 from /usr/local/R/3.2.1/lib64/R/library/Rcpp/include/RcppCommon.h:62,
                 from /usr/local/R/3.2.1/lib64/R/library/Rcpp/include/Rcpp.h:27,
                 from StringVectorExample.cpp:22:
/usr/local/gcc/4.9.1/include/c++/4.9.1/bits/stl_algo.h: In instantiation of ‘_OIter std::transform(_IIter, _IIter, _OIter, _UnaryOperation) [with _IIter = SEXPREC* const*; _OIter = Rcpp::internal::Proxy_Iterator<Rcpp::internal::string_proxy<16> >; _UnaryOperation = Rcpp::StringTransformer<int(int) throw ()>]’:
StringVectorExample.cpp:30:38:   required from here
/usr/local/gcc/4.9.1/include/c++/4.9.1/bits/stl_algo.h:4163:33: error: no match for call to ‘(Rcpp::StringTransformer<int(int) throw ()>) (SEXPREC* const&)’
  *__result = __unary_op(*__first);
                                 ^
In file included from /usr/local/R/3.2.1/lib64/R/library/Rcpp/include/Rcpp.h:54:0,
                 from StringVectorExample.cpp:22:
/usr/local/R/3.2.1/lib64/R/library/Rcpp/include/Rcpp/StringTransformer.h:30:8: note: candidate is:
  class StringTransformer : public std::unary_function<const char*, const char*>{
        ^
/usr/local/R/3.2.1/lib64/R/library/Rcpp/include/Rcpp/StringTransformer.h:35:15: note: const char* Rcpp::StringTransformer<UnaryOperator>::operator()(const char*) [with UnaryOperator = int(int) throw ()]
   const char* operator()(const char* input ) {
               ^
/usr/local/R/3.2.1/lib64/R/library/Rcpp/include/Rcpp/StringTransformer.h:35:15: note:   no known conversion for argument 1 from ‘SEXPREC* const’ to ‘const char*’
make: *** [StringVectorExample.o] Error 1
ERROR: compilation failed for package ‘RcppExamples’
`

**Comment by eddelbuettel** [comment]
Works for me, works for Travis CI, works for CRAN.  

Can you share details, eg why are all those unrelated header files included?

**Comment by lancewilson-monash** [comment]
The compile is on a HPC cluster running Centos 6.5. The header files are from the build environment that is used for most of the source installed software. There is also a bug report here - https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16687

I just did some more checking and one of the modules was in conflict. The compile line that now works is:
`g++ -I/usr/local/R/3.2.1/lib64/R/include -DNDEBUG  -I/usr/local/openmpi/1.8.2-gcc/include -I/usr/local/gcc/4.9.1/include/c++/4.9.1/x86_64-unknown-linux-gnu/ -I/usr/local/gcc/4.9.1/include -I/usr/local/mpc/1.0.2/include -I/usr/local/mpfr/3.1.2/include -I/usr/local/gmp/6.0.0/include -I"/home/userXX/R/x86_64-unknown-linux-gnu-library/3.2/Rcpp/include"   -fpic  -g -O2  -c StringVectorExample.cpp -o StringVectorExample.o`

Thanks for getting back to me so quickly! Hope this info helps.

**Comment by lancewilson-monash** [comment]
Just tried to install the pack as an admin user and it failed again

`g++ -I/usr/local/R/3.2.1/lib64/R/include -DNDEBUG  -I/usr/local/openmpi/1.8.2-gcc/include -I/usr/local/gcc/4.9.1/include/c++/4.9.1/x86_64-unknown-linux-gnu/ -I/usr/local/gcc/4.9.1/include -I/usr/local/mpc/1.0.2/include -I/usr/local/mpfr/3.1.2/include -I/usr/local/gmp/6.0.0/include -I"/usr/local/R/3.2.1/lib64/R/library/Rcpp/include"   -fpic  -g -O2  -c StringVectorExample.cpp -o StringVectorExample.o
In file included from /usr/local/gcc/4.9.1/include/c++/4.9.1/algorithm:62:0,
                 from /usr/local/R/3.2.1/lib64/R/library/Rcpp/include/RcppCommon.h:62,
                 from /usr/local/R/3.2.1/lib64/R/library/Rcpp/include/Rcpp.h:27,
                 from StringVectorExample.cpp:22:
/usr/local/gcc/4.9.1/include/c++/4.9.1/bits/stl_algo.h: In instantiation of ‘_OIter std::transform(_IIter, _IIter, _OIter, _UnaryOperation) [with _IIter = SEXPREC\* const_; _OIter = Rcpp::internal::Proxy_IteratorRcpp::internal::string_proxy<16 >; _UnaryOperation = Rcpp::StringTransformer<int(int) throw ()>]’:
StringVectorExample.cpp:30:38:   required from here
/usr/local/gcc/4.9.1/include/c++/4.9.1/bits/stl_algo.h:4163:33: error: no match for call to ‘(Rcpp::StringTransformer<int(int) throw ()>) (SEXPREC_ const&)’
  ___result = __unary_op(___first);
                                 ^
In file included from /usr/local/R/3.2.1/lib64/R/library/Rcpp/include/Rcpp.h:54:0,
                 from StringVectorExample.cpp:22:
/usr/local/R/3.2.1/lib64/R/library/Rcpp/include/Rcpp/StringTransformer.h:30:8: note: candidate is:
  class StringTransformer : public std::unary_function<const char*, const char*>{
        ^
/usr/local/R/3.2.1/lib64/R/library/Rcpp/include/Rcpp/StringTransformer.h:35:15: note: const char\* Rcpp::StringTransformer<UnaryOperator>::operator()(const char_) [with UnaryOperator = int(int) throw ()]
   const char_ operator()(const char\* input ) {
               ^
/usr/local/R/3.2.1/lib64/R/library/Rcpp/include/Rcpp/StringTransformer.h:35:15: note:   no known conversion for argument 1 from ‘SEXPREC\* const’ to ‘const char_’
make: *_\* [StringVectorExample.o] Error 1
ERROR: compilation failed for package ‘RcppExamples’
- removing ‘/usr/local/R/3.2.1/lib64/R/library/RcppExamples’
  `

**Comment by lancewilson-monash** [comment]
If you have the previous version (0.1.6) installed then the new version compiles. Without it the compile fails. Repeatable as both admin and normal user.

**Comment by eddelbuettel** [comment]
Still your local problem with your cluster setup and the mixing of various things.

_If you built as R wants you to build via R CMD INSTALL on the package_ then it works. It is also all I am responsible for.  The rest, really, is your making.  Sorry.

**Comment by lancewilson-monash** [comment]
I probably need to clarify that the error message are from inside R not a compile from a shell. i just copied the relevant lines of output.

The install was done using the recommended method of:
packages.install(RcppExamples)

**Comment by eddelbuettel** [comment]
Your R installation is non-standard with those mpi and mpfr and whatnot headers. 

And for failure on non-standard platforms with Irreproducible issues I simply cannot help you.
